# Generated by Django 3.2.6 on 2021-09-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('IN', 'Indoor'), ('OUT', 'Outdoor'), ('SUC', 'Saculent'), ('SE', 'Seasonal'), ('OTH', 'Others')], max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
